name: BankAPI
authors: [adamags]
description: A banking system in Minecraft
version: 1.0
#api-version: 1.19
main: bankapi.BankMain
commands:
  balance:
    description: Shows your current balance in the bank.
    usage: /balance
  send:
    description: Sends amount to another player, they must be online
    usage: /send [amount] player
  baltop:
    description: Gives top balances on the server
    usage: /baltop
